language: python
dist: trusty
python:
   - "2.7"
   - "3.4"
   - "3.5"
   - "3.6"
before_install:
  - sudo apt-get update
install:
  - "pip install -r dev_requirements.txt"
# command to run tests
script:
  - py.test --cov lifetimes --mpl --mpl-baseline-path tests/reference_plots/
after_success:
  coveralls
# Don't want notifications
notifications:
  email: false
